### ISSUE TITLE
Produzir POC com propriedade `mapping` para armazenamento da lista de referência cruzada entre classificações

### ISSUE THREAD

**Issue by fjuniorr** [splor-mg/ementario#3]
Uma estrutura pode ser

```yaml
mapping:
  - from:
    to:
    ref: # para que não seja necessário transformações durante lookup das descrições
    valid_from:
    valid_to: # para que seja possível indicar que um mapeamento não é mais válido tendo em vista desbloqueio de classificação
```

Mas falta entender as 

- as necessidades de informação que devem ser atendidas;
- as convenções já existentes para divulgação de tabelas de_para (eg. usadas pela STN para plano de contas e ementário);

![20230525T110623](https://github.com/splor-mg/ementario/assets/4969445/fcc4db70-c1d5-4a87-9321-8ffaa860aa55)

- o significado da operação de transposição parcial. Exemplo para a classificação _17135000 - Transferências de Recursos do Sistema Único de Saúde – SUS – Repasses Fundo a Fundo - Bloco de Manutenção das Ações e Serviços Públicos de Saúde_:

![ement-receita_de-para-2022-2023](https://github.com/splor-mg/ementario/assets/4969445/7b1e7356-8f97-474b-971f-8077fbd2748a)
